/** HTTP path constants shared by service handlers and HTTP clients. */

export const MEMORIES_HTTP_PATH = {
  wellKnown: "/.well-known/memories",
  health: "/health",
  databases: "/databases",
  databasesOpen: "/databases/open",
  databasesMetadataGet: "/databases/metadata/get",
  databasesMetadataUpsert: "/databases/metadata/upsert",
  databasesExists: "/databases/exists",
  databasesCheckpoint: "/databases/checkpoint",
  databasesClose: "/databases/close",
  databasesSearch: "/databases/search",
  databasesSearchNamespaces: "/databases/search-namespaces",
  databasesMerge: "/databases/merge",
  databasesDeleteMemory: "/databases/delete-memory",
  databasesSuppressMemory: "/databases/suppress-memory",
  databasesUnsuppressMemory: "/databases/unsuppress-memory",
  databasesSuppressNamespace: "/databases/suppress-namespace",
  databasesUnsuppressNamespace: "/databases/unsuppress-namespace",
  databasesProvenanceHead: "/databases/provenance/head",
  databasesProvenanceTimestamp: "/databases/provenance/timestamp",
  databasesProvenanceEvents: "/databases/provenance/events",
  databasesProvenanceChain: "/databases/provenance/chain",
  databasesProvenanceContent: "/databases/provenance/content",
  databasesProvenanceGraph: "/databases/provenance/graph",
  databasesProvenanceVectors: "/databases/provenance/vectors",
  databasesMemoryDetail: "/databases/memory-detail",
  databasesEdgeDetail: "/databases/edge-detail",
  databasesCapabilities: "/databases/capabilities",
  databasesNamespaces: "/databases/namespaces",
  databasesNamespacesUnderPrefix: "/databases/namespaces/under-prefix",
  databasesNamespacesExistsUnderPrefix: "/databases/namespaces/exists-under-prefix",
  databasesNamespacesGet: "/databases/namespaces/get",
  databasesNamespacesUpsert: "/databases/namespaces/upsert",
  databasesNamespacesDelete: "/databases/namespaces/delete",
  databasesNamespacesRename: "/databases/namespaces/rename",
  databasesEdgePreview: "/databases/edge-preview",
  databasesMemoryPreview: "/databases/memory-preview",
  databasesSourceMapTextPreview: "/databases/source-map/text-preview",
  databasesSourceMapText: "/databases/source-map/text",
  databasesSourceMapReplace: "/databases/source-map/replace",
  databasesVectorDimensions: "/databases/vector-dimensions",
  databasesGraphLayout: "/databases/graph-layout",
  databasesGraphCounts: "/databases/graph-counts",
  databasesGraphStats: "/databases/graph-stats",
  databasesProjectionInput: "/databases/projections/projection-input",
  databasesEnsureScopeChain: "/databases/ensure-scope-chain",
  databasesFindMemoryId: "/databases/find-memory-id",
  databasesEffectiveSuppression: "/databases/effective-suppression",
  databasesLoadMemoryNamespaceKey: "/databases/load-memory-namespace-key",
  databasesOntologyLink: "/databases/ontology/link",
  databasesOntologyCurrent: "/databases/ontology/current",
  databasesHash: "/databases/hash",
  databasesOntologyHistory: "/databases/ontology/history",
  ontologiesRegister: "/ontologies/register",
  ontologiesGet: "/ontologies/get",
  ontologiesDatabases: "/ontologies/databases",
} as const;

export type MemoriesHttpPathKey = keyof typeof MEMORIES_HTTP_PATH;
