/** @deprecated Import from @khoralabs/memories-persistence-core instead. */
export {
  canonicalizeNamespacePrefixes,
  isPrefixOf,
  MEMORY_NAMESPACE_PATH_REGEX,
  NAMESPACE_MAX_DEPTH,
  NAMESPACE_SEGMENT_REGEX,
  NAMESPACE_SEPARATOR,
  type NamespacePath,
  type NamespacePathLiteral,
  type NamespacePrefixKey,
  type NamespacePrefixKeyCamel,
  NS_PREFIX_KEYS,
  NS_PREFIX_KEYS_CAMEL,
  namespaceFromSegments,
  namespaceLevels,
  namespacePath,
  namespacePrefixFieldForDepth,
  namespacePrefixFieldForDepthCamel,
  namespacePrefixFields,
  namespacePrefixFieldsCamel,
  namespaceSegments,
  zNamespacePath,
} from "@khoralabs/memories-persistence-core";
