/**
 * Node/operator barrel: lean HTTP client + ontology + remote clients.
 * Prefer `@khoralabs/memories-service/client/http` in browser/Next client code.
 */

export {
  type DiscoverMemoriesServiceOptions,
  discoverMemoriesService,
} from "./discover";
export * from "./http";
export * from "./ontology";
export {
  createDeferredRemoteMemoriesClientAsync,
  createRemoteMemoriesClientAsync,
  createRemoteMemoriesReadClient,
  RemoteMemoriesClientAsync,
  type RemoteMemoriesClientAsyncOptions,
  RemoteMemoriesReadClient,
  type RemoteMemoriesReadClientOptions,
  readyDeferredRemoteMemoriesClientAsync,
} from "./remote-client";
export {
  type DatabaseCapabilitiesResponse,
  type DatabaseDeleteMemoryRequest,
  type DatabaseEdgePreviewRequest,
  type DatabaseEffectiveSuppressionRequest,
  type DatabaseEffectiveSuppressionResponse,
  type DatabaseGraphCountsRequest,
  type DatabaseGraphCountsResponse,
  type DatabaseGraphLayoutRequest,
  type DatabaseGraphStatsRequest,
  type DatabaseGraphStatsResponse,
  type DatabaseHashRequest,
  type DatabaseHashResponse,
  type DatabaseListEntry,
  type DatabaseListResponse,
  type DatabaseMemoryPreviewRequest,
  type DatabaseMemoryPreviewResponse,
  type DatabaseMergeRequest,
  type DatabaseMetadataGetRequest,
  type DatabaseMetadataGetResponse,
  type DatabaseMetadataUpsertRequest,
  type DatabaseMetadataUpsertResponse,
  type DatabaseNamespaceDeleteRequest,
  type DatabaseNamespaceDeleteResponse,
  type DatabaseNamespaceExistsUnderPrefixRequest,
  type DatabaseNamespaceExistsUnderPrefixResponse,
  type DatabaseNamespaceGetRequest,
  type DatabaseNamespaceGetResponse,
  type DatabaseNamespaceMetadata,
  type DatabaseNamespaceRenameRequest,
  type DatabaseNamespaceRenameResponse,
  type DatabaseNamespacesRequest,
  type DatabaseNamespacesResponse,
  type DatabaseNamespacesUnderPrefixRequest,
  type DatabaseNamespacesUnderPrefixResponse,
  type DatabaseNamespaceUpsertRequest,
  type DatabaseNamespaceUpsertResponse,
  type DatabaseProjectionInputRequest,
  type DatabaseProvenanceChainLink,
  type DatabaseProvenanceChainRequest,
  type DatabaseProvenanceChainResponse,
  type DatabaseProvenanceContentRequest,
  type DatabaseProvenanceContentResponse,
  type DatabaseProvenanceEventItem,
  type DatabaseProvenanceEventsRequest,
  type DatabaseProvenanceEventsResponse,
  type DatabaseProvenanceHeadResponse,
  type DatabaseProvenanceTimestampRequest,
  type DatabaseProvenanceTimestampResponse,
  type DatabaseSearchNamespacesRequest,
  type DatabaseSearchNamespacesResponse,
  type DatabaseSearchRequest,
  type DatabaseSearchResponse,
  type DatabaseSourceMapReplaceRequest,
  type DatabaseSourceMapReplaceResponse,
  type DatabaseSourceMapTextPreviewRequest,
  type DatabaseSourceMapTextPreviewResponse,
  type DatabaseSourceMapTextRequest,
  type DatabaseSourceMapTextResponse,
  type DatabaseSuppressMemoryRequest,
  type DatabaseSuppressMemoryResponse,
  type DatabaseSuppressNamespaceRequest,
  type DatabaseSuppressNamespaceResponse,
  type DatabaseUnsuppressMemoryRequest,
  type DatabaseUnsuppressMemoryResponse,
  type DatabaseUnsuppressNamespaceRequest,
  type DatabaseUnsuppressNamespaceResponse,
  type DatabaseVectorDimensionsRequest,
  type DeleteMemoryParamsWire,
  deserializeSearchHit,
  deserializeSearchHits,
  type GraphEdgeLinkWire,
  type MemoryWire,
  type OntologyLabelWire,
  type SearchContentWire,
  type SearchHitWire,
  type SearchNeighborHitWire,
  type SearchParamsWire,
  type SuppressMemoryParamsWire,
  type SuppressNamespaceParamsWire,
  serializeSearchHit,
} from "./wire";
